# Generated by Django 5.0.2 on 2024-03-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='major_skill',
        ),
    ]
